[[redirects]]
  from = "/api"
  to = "https://yozrvvzd96.execute-api.us-east-1.amazonaws.com/v1/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"